implemented spec
EstiSchottenstein/daycamp pull request #2
Opened 2023-11-19 11:09 UTC by AshiraFriedman

Please review my work, let me know if there are any corrections

2023-11-19 19:54 UTC, EstiSchottenstein requested changes
I reviewed your work. Everything looks good, there were just two small mistakes. Please see my inline comments.

2023-11-19 19:54 UTC, EstiSchottenstein commented on 3 reports.sql
> +select c.FirstName, LastName = concat(c.LastName, ' warning!'), c.Allergies
The word warning should be in parenthesis like this: (warning!)

2023-11-19 19:54 UTC, EstiSchottenstein commented on 2 data.sql
> +union select 'Chana', 'Braun', 1,' Beis Sarah', 2169852492, 7322038038, null, null, 'both', 1, 1
There is an extra space before the name of the school.

2023-11-20 07:54 UTC, AshiraFriedman commented on 2 data.sql
> +union select 'Chana', 'Braun', 1,' Beis Sarah', 2169852492, 7322038038, null, null, 'both', 1, 1
I removed it

2023-11-20 07:54 UTC, closed without merging